# Data paths
data_path: "data/constellation_dataset_1"
log_dir: "logs"

# Model configuration
model:
  backbone: "resnet50"
  dropout_rate: 0.5

# Training configuration
training:
  learning_rate: 1e-4
  weight_decay: 1e-5
  optimizer: "adamw"
  batch_size: 32
  num_workers: 4
  num_epochs: 10
  
  # Scheduler configuration
  scheduler_type: "cosine"
  warmup_epochs: 3
  min_lr: 1e-6
  max_lr: 1e-3
  warmup_start_lr: 1e-7
  cosine_cycles: 3
  plateau_patience: 3
  plateau_factor: 0.5
  verbose: true

# Logging configuration
logging:
  use_wandb: true
  project_name: "constellation-classification"
  tags: ["resnet", "multi-label"]
  name: "cnns"